import type { QuizQuestion } from "@/components/courses/quiz-panel";

/** Course-specific assessment banks (8–10 questions each). */
export const COURSE_QUIZ_BANKS: Record<string, QuizQuestion[]> = {
  "web-foundations": [
    { id: "wf-q1", prompt: "Which language describes the structure and meaning of a web page?", choices: ["CSS", "HTML", "JavaScript", "SQL"], correctIndex: 1 },
    { id: "wf-q2", prompt: "What does CSS primarily control?", choices: ["Server routes", "Presentation and layout", "Database schema", "Git history"], correctIndex: 1 },
    { id: "wf-q3", prompt: "Why prefer semantic tags like <main> and <nav>?", choices: ["They make the file smaller only", "Accessibility, SEO, and clearer structure", "They replace CSS", "Browsers ignore them"], correctIndex: 1 },
    { id: "wf-q4", prompt: "In the CSS box model, which layer sits between content and border?", choices: ["Margin", "Padding", "Outline", "Z-index"], correctIndex: 1 },
    { id: "wf-q5", prompt: "What does box-sizing: border-box do?", choices: ["Ignores padding entirely", "Includes padding and border inside the element's width", "Only works on flex containers", "Removes margins"], correctIndex: 1 },
    { id: "wf-q6", prompt: "Which Flexbox property distributes space along the main axis?", choices: ["align-items", "justify-content", "flex-direction only", "z-index"], correctIndex: 1 },
    { id: "wf-q7", prompt: "What is a mobile-first media query approach?", choices: ["Write desktop CSS first, then delete it", "Base styles for small screens, then enhance with min-width queries", "Never use CSS", "Only use max-width: 320px forever"], correctIndex: 1 },
    { id: "wf-q8", prompt: "Every form control should have…", choices: ["A random id only", "An associated label", "Inline JavaScript", "No name attribute"], correctIndex: 1 },
    { id: "wf-q9", prompt: "DevTools Elements panel shows…", choices: ["Only the original HTML file on disk", "The live DOM the browser built", "SQL tables", "Git commits"], correctIndex: 1 },
    { id: "wf-q10", prompt: "Which is a good landing-page structure?", choices: ["Random divs with no headings", "Header/nav, hero, features, footer with semantic landmarks", "Only images, no text", "A single <canvas> for everything"], correctIndex: 1 },
  ],
  "javascript-mastery": [
    { id: "js-q1", prompt: "Which keyword should you prefer for values that do not get reassigned?", choices: ["var", "let", "const", "static"], correctIndex: 2 },
    { id: "js-q2", prompt: "What does typeof null return in JavaScript?", choices: ['"null"', '"object"', '"undefined"', '"number"'], correctIndex: 1 },
    { id: "js-q3", prompt: "Which comparison is safer for equality checks?", choices: ["==", "===", "=", "<>"], correctIndex: 1 },
    { id: "js-q4", prompt: "What does array.map() return?", choices: ["A single number", "A new array with transformed items", "Nothing (undefined only)", "A DOM node"], correctIndex: 1 },
    { id: "js-q5", prompt: "array.filter(fn) keeps items where fn returns…", choices: ["false", "true", "null", "a string only"], correctIndex: 1 },
    { id: "js-q6", prompt: "A pure function…", choices: ["Always writes to the DOM", "Same inputs → same output, no hidden side effects", "Must use async/await", "Cannot take parameters"], correctIndex: 1 },
    { id: "js-q7", prompt: "What does await do inside an async function?", choices: ["Blocks the entire operating system", "Pauses that function until the Promise settles", "Deletes the Promise", "Converts code to CSS"], correctIndex: 1 },
    { id: "js-q8", prompt: "addEventListener is used to…", choices: ["Style an element", "Run code when a DOM event happens", "Create a SQL index", "Commit Git changes"], correctIndex: 1 },
    { id: "js-q9", prompt: "Which structure is best for a list of ordered scores?", choices: ["Object only", "Array", "Function", "CSS class"], correctIndex: 1 },
    { id: "js-q10", prompt: "fetch() returns a…", choices: ["string", "Promise", "number", "HTMLElement"], correctIndex: 1 },
  ],
  "python-for-beginners": [
    { id: "py-q1", prompt: "Which type represents whole numbers in Python?", choices: ["str", "int", "dict", "bool only"], correctIndex: 1 },
    { id: "py-q2", prompt: "What does an f-string do?", choices: ["Formats a string with embedded expressions", "Opens a file", "Defines a class", "Imports a module"], correctIndex: 0 },
    { id: "py-q3", prompt: "Preferred naming style for Python variables?", choices: ["camelCase", "snake_case", "SCREAMING", "kebab-case"], correctIndex: 1 },
    { id: "py-q4", prompt: "What does range(1, 6) produce when iterated?", choices: ["1 through 6 inclusive", "1 through 5", "0 through 6", "Only 6"], correctIndex: 1 },
    { id: "py-q5", prompt: "A list comprehension like [n*n for n in nums]…", choices: ["Builds a new list", "Always returns a dict", "Deletes nums", "Only works in JavaScript"], correctIndex: 0 },
    { id: "py-q6", prompt: "dict.get(\"key\") is safer than dict[\"key\"] because…", choices: ["It is faster always", "It can return a default instead of raising KeyError", "It sorts the dict", "It converts keys to int"], correctIndex: 1 },
    { id: "py-q7", prompt: "Why use a with block when opening files?", choices: ["It is optional decoration only", "It ensures the file is closed properly", "It encrypts the file", "It uploads to the cloud"], correctIndex: 1 },
    { id: "py-q8", prompt: "def grade(score: int) -> str: declares…", choices: ["A variable named grade", "A function with parameter and return type hints", "A SQL query", "A CSS rule"], correctIndex: 1 },
    { id: "py-q9", prompt: "sys.argv is used to…", choices: ["Style the terminal", "Read command-line arguments", "Connect to Postgres", "Render HTML"], correctIndex: 1 },
    { id: "py-q10", prompt: "Which is a boolean value in Python?", choices: ["true", "True", "TRUE", "yes"], correctIndex: 1 },
  ],
  "react-essentials": [
    { id: "re-q1", prompt: "A React component is best described as…", choices: ["A CSS file only", "A reusable piece of UI driven by props and state", "A SQL table", "A Git branch"], correctIndex: 1 },
    { id: "re-q2", prompt: "Props are…", choices: ["Mutable internal state only", "Inputs passed into a component from its parent", "Database rows", "CSS variables only"], correctIndex: 1 },
    { id: "re-q3", prompt: "useState is used to…", choices: ["Fetch CSS", "Hold local component state that can change over time", "Define routes", "Commit Git changes"], correctIndex: 1 },
    { id: "re-q4", prompt: "A controlled input means…", choices: ["The DOM owns the value only", "React state is the source of truth for the input value", "The input cannot change", "It must be type=password"], correctIndex: 1 },
    { id: "re-q5", prompt: "useEffect runs…", choices: ["Only during server SQL queries", "After render, for side effects like fetching", "Before the HTML file is saved", "Instead of return JSX"], correctIndex: 1 },
    { id: "re-q6", prompt: "When mapping a list to components you should provide…", choices: ["No key", "A stable unique key", "Only inline styles", "A random key every render"], correctIndex: 1 },
    { id: "re-q7", prompt: "JSX must…", choices: ["Return multiple root siblings without a parent in older rules", "Express UI structure that compiles to React elements", "Be written in a .css file", "Never use expressions"], correctIndex: 1 },
    { id: "re-q8", prompt: "Lifting state up means…", choices: ["Moving state to a common parent so siblings can share it", "Deleting state", "Putting state only in CSS", "Using localStorage only"], correctIndex: 0 },
  ],
  "git-professional-workflow": [
    { id: "git-q1", prompt: "Git primarily tracks…", choices: ["Only file sizes", "Snapshots of your project over time", "CPU usage", "CSS specificity"], correctIndex: 1 },
    { id: "git-q2", prompt: "What does git add do?", choices: ["Pushes to GitHub", "Stages changes for the next commit", "Deletes the repo", "Runs tests"], correctIndex: 1 },
    { id: "git-q3", prompt: "A good commit message should…", choices: ["Say only 'update'", "Explain why the change exists in clear language", "Be empty", "Include the full diff only"], correctIndex: 1 },
    { id: "git-q4", prompt: "A branch is…", choices: ["A separate computer", "A movable pointer to a series of commits", "A CSS media query", "A SQL JOIN"], correctIndex: 1 },
    { id: "git-q5", prompt: "git push uploads commits to a…", choices: ["local only folder", "remote such as origin", "browser cache", "DNS server"], correctIndex: 1 },
    { id: "git-q6", prompt: "A pull request is mainly for…", choices: ["Hiding code forever", "Proposing and reviewing changes before merging", "Formatting CSS", "Paying certificates"], correctIndex: 1 },
    { id: "git-q7", prompt: "Which is safer for undoing a public commit already shared?", choices: ["git push --force always", "git revert (new commit that undoes)", "Delete .git", "Ignore it"], correctIndex: 1 },
    { id: "git-q8", prompt: ".gitignore is used to…", choices: ["Style ignored files", "Keep secrets and build artifacts out of commits", "Speed up JavaScript", "Replace branching"], correctIndex: 1 },
  ],
  "sql-databases": [
    { id: "sql-q1", prompt: "SELECT is used to…", choices: ["Delete a database", "Read rows from tables", "Style HTML", "Commit Git"], correctIndex: 1 },
    { id: "sql-q2", prompt: "WHERE filters…", choices: ["Columns only", "Rows based on a condition", "Only table names", "Indexes only"], correctIndex: 1 },
    { id: "sql-q3", prompt: "ORDER BY…", choices: ["Deletes rows", "Sorts the result set", "Creates a user", "Runs JavaScript"], correctIndex: 1 },
    { id: "sql-q4", prompt: "INNER JOIN returns…", choices: ["All rows from both tables always", "Only rows with matching keys in both tables", "No rows ever", "Only column names"], correctIndex: 1 },
    { id: "sql-q5", prompt: "LEFT JOIN keeps…", choices: ["Only right table orphans", "All left rows, matched right data or NULL", "Duplicates only", "Nothing"], correctIndex: 1 },
    { id: "sql-q6", prompt: "GROUP BY is typically used with…", choices: ["Git branches", "Aggregate functions like COUNT or SUM", "CSS flex", "React props"], correctIndex: 1 },
    { id: "sql-q7", prompt: "A primary key should be…", choices: ["Nullable and duplicated", "Unique per row", "A CSS class", "Optional always"], correctIndex: 1 },
    { id: "sql-q8", prompt: "LIMIT 10…", choices: ["Deletes 10 tables", "Returns at most 10 rows", "Creates 10 indexes", "Runs 10 times slower always"], correctIndex: 1 },
  ],
  "typescript-for-developers": [
    { id: "ts-q1", prompt: "TypeScript's main benefit over plain JavaScript is…", choices: ["Faster network only", "Static types that catch errors before runtime", "Replacing HTML", "Removing CSS"], correctIndex: 1 },
    { id: "ts-q2", prompt: "Which keyword declares a type alias?", choices: ["class", "type", "module", "var"], correctIndex: 1 },
    { id: "ts-q3", prompt: "An interface is typically used to…", choices: ["Style components", "Describe the shape of an object", "Query SQL", "Commit Git"], correctIndex: 1 },
    { id: "ts-q4", prompt: "A union type like string | number means…", choices: ["Always both at once", "Either string or number", "Only null", "Only arrays"], correctIndex: 1 },
    { id: "ts-q5", prompt: "Generics let you…", choices: ["Write CSS", "Parameterize types for reusable functions/structures", "Delete types", "Skip compilation"], correctIndex: 1 },
    { id: "ts-q6", prompt: "Narrowing means…", choices: ["Making fonts smaller", "Refining a broad type to a more specific one in a branch", "Minifying JS only", "Closing a file"], correctIndex: 1 },
    { id: "ts-q7", prompt: "strict mode in tsconfig helps by…", choices: ["Disabling types", "Enabling stronger type checks", "Only formatting code", "Replacing ESLint"], correctIndex: 1 },
    { id: "ts-q8", prompt: "Typing an API response helps you…", choices: ["Ignore errors", "Know field names and avoid typos at compile time", "Speed up DNS", "Hide network failures"], correctIndex: 1 },
  ],
  "nextjs-fullstack": [
    { id: "nx-q1", prompt: "In the App Router, a layout.tsx file…", choices: ["Only runs on the client", "Wraps nested routes and persists across navigations", "Replaces package.json", "Is a CSS file"], correctIndex: 1 },
    { id: "nx-q2", prompt: "When do you add 'use client'?", choices: ["On every file always", "When the module needs browser APIs or React state/effects", "Never in Next.js", "Only in API routes"], correctIndex: 1 },
    { id: "nx-q3", prompt: "Server Components by default…", choices: ["Cannot fetch data", "Run on the server and can fetch without shipping that logic to the browser", "Are only for CSS", "Replace databases"], correctIndex: 1 },
    { id: "nx-q4", prompt: "Server Actions are useful for…", choices: ["Only static images", "Mutations and form handling without a separate REST handler", "DNS only", "Git commits"], correctIndex: 1 },
    { id: "nx-q5", prompt: "page.tsx in app/courses/[slug] is…", choices: ["A global CSS rule", "A dynamic route page for one course", "A Paystack key", "An SQL table"], correctIndex: 1 },
    { id: "nx-q6", prompt: "Protecting a dashboard route usually means…", choices: ["Hiding the nav only", "Checking auth on the server and redirecting if unsigned-in", "Disabling JavaScript", "Using only localStorage"], correctIndex: 1 },
    { id: "nx-q7", prompt: "Metadata in layout/page exports helps with…", choices: ["Git branching", "SEO and social previews (title/description)", "SQL joins", "Paystack webhooks"], correctIndex: 1 },
    { id: "nx-q8", prompt: "Nested routes share UI via…", choices: ["Only iframes", "Layouts and optional parallel routes", "CSS !important", "Email only"], correctIndex: 1 },
  ],
  "backend-apis-node": [
    { id: "be-q1", prompt: "HTTP GET is typically used to…", choices: ["Delete permanent data only", "Read resources without side effects", "Always create rows", "Style HTML"], correctIndex: 1 },
    { id: "be-q2", prompt: "Status 201 usually means…", choices: ["Not found", "Created", "Unauthorized", "Server error"], correctIndex: 1 },
    { id: "be-q3", prompt: "Status 401 means…", choices: ["OK", "Unauthorized (not authenticated)", "Redirect", "Conflict only"], correctIndex: 1 },
    { id: "be-q4", prompt: "Validating input on the server is important because…", choices: ["Clients are always trusted", "Clients can be bypassed or malicious", "It replaces TLS", "SQL is optional"], correctIndex: 1 },
    { id: "be-q5", prompt: "JSON in APIs is commonly used to…", choices: ["Store only images", "Exchange structured data between client and server", "Replace Git", "Compile TypeScript"], correctIndex: 1 },
    { id: "be-q6", prompt: "Pagination helps by…", choices: ["Loading the entire table always", "Returning limited pages of results", "Deleting indexes", "Disabling caches"], correctIndex: 1 },
    { id: "be-q7", prompt: "Sessions/cookies on the server help…", choices: ["Style pages", "Remember who the user is across requests", "Generate CSS", "Replace HTTPS"], correctIndex: 1 },
    { id: "be-q8", prompt: "Status 403 means…", choices: ["Success", "Forbidden (authenticated but not allowed)", "Found", "No content only"], correctIndex: 1 },
  ],
  "html-css-advanced": [
    { id: "hc-q1", prompt: "CSS Grid is best for…", choices: ["One-dimensional rows only", "Two-dimensional page layouts", "Database joins", "Git branching"], correctIndex: 1 },
    { id: "hc-q2", prompt: "clamp() is useful for…", choices: ["SQL limits", "Fluid typography and spacing between min and max", "Deleting CSS", "Only animations"], correctIndex: 1 },
    { id: "hc-q3", prompt: "Custom properties (CSS variables) start with…", choices: ["$", "--", "var.", "@"], correctIndex: 1 },
    { id: "hc-q4", prompt: "prefers-reduced-motion helps…", choices: ["Faster SQL", "Accessibility by reducing animation", "SEO only", "Paystack"], correctIndex: 1 },
    { id: "hc-q5", prompt: "A good class naming approach is…", choices: ["Random strings", "Consistent, readable patterns", "Only inline styles forever", "IDs for everything"], correctIndex: 1 },
    { id: "hc-q6", prompt: "Container queries let styles react to…", choices: ["Only the viewport", "The size of a parent container", "Git status", "DNS"], correctIndex: 1 },
    { id: "hc-q7", prompt: "aspect-ratio is used to…", choices: ["Encrypt video", "Maintain width/height proportions", "Sort tables", "Hash passwords"], correctIndex: 1 },
    { id: "hc-q8", prompt: "Logical properties like margin-inline help with…", choices: ["Only print CSS", "Writing-direction aware spacing", "SQL indexes", "Node versions"], correctIndex: 1 },
  ],
  "data-structures-algorithms": [
    { id: "dsa-q1", prompt: "Big-O describes…", choices: ["Exact runtime in ms always", "How runtime/space grow as input grows", "Only memory brand", "CSS specificity"], correctIndex: 1 },
    { id: "dsa-q2", prompt: "An array gives O(1) access by…", choices: ["Value search always", "Index", "Hash only", "Sorting first"], correctIndex: 1 },
    { id: "dsa-q3", prompt: "A stack is…", choices: ["FIFO", "LIFO", "Random access tree", "SQL view"], correctIndex: 1 },
    { id: "dsa-q4", prompt: "A queue is…", choices: ["LIFO", "FIFO", "A hash map", "A CSS grid"], correctIndex: 1 },
    { id: "dsa-q5", prompt: "Hash maps average O(1) for…", choices: ["Sorting only", "Key lookup/insert", "Rendering DOM", "Git merge"], correctIndex: 1 },
    { id: "dsa-q6", prompt: "Binary search requires…", choices: ["Unsorted data", "Sorted data", "A GPU", "CSS flex"], correctIndex: 1 },
    { id: "dsa-q7", prompt: "Recursion must eventually…", choices: ["Grow stack forever", "Hit a base case", "Call SQL", "Disable types"], correctIndex: 1 },
    { id: "dsa-q8", prompt: "A graph is made of…", choices: ["Only arrays", "Nodes and edges", "Only CSS", "Certificates"], correctIndex: 1 },
  ],
  "cybersecurity-basics": [
    { id: "cy-q1", prompt: "Phishing aims to…", choices: ["Speed up CSS", "Trick users into revealing secrets", "Compile TypeScript", "Sort arrays"], correctIndex: 1 },
    { id: "cy-q2", prompt: "HTTPS primarily provides…", choices: ["Faster images only", "Encrypted transport and server authenticity", "Free hosting", "Git history"], correctIndex: 1 },
    { id: "cy-q3", prompt: "Least privilege means…", choices: ["Everyone is admin", "Grant only the access needed", "Disable passwords", "Share one account"], correctIndex: 1 },
    { id: "cy-q4", prompt: "A strong password should be…", choices: ["Your name + 123", "Long, unique, and hard to guess", "Written in HTML comments", "The same everywhere"], correctIndex: 1 },
    { id: "cy-q5", prompt: "MFA adds…", choices: ["Another CSS file", "A second factor beyond password", "SQL triggers only", "Dark mode"], correctIndex: 1 },
    { id: "cy-q6", prompt: "SQL injection is mitigated by…", choices: ["String concat of all input", "Parameterized queries / validation", "Disabling HTTPS", "Using only GET"], correctIndex: 1 },
    { id: "cy-q7", prompt: "XSS is about…", choices: ["Git branches", "Injecting scripts into pages viewed by others", "Faster React", "Docker only"], correctIndex: 1 },
    { id: "cy-q8", prompt: "Keeping software updated helps…", choices: ["Only UI polish", "Close known security holes", "Replace backups", "Avoid types"], correctIndex: 1 },
  ],
  "mobile-react-native": [
    { id: "rn-q1", prompt: "React Native builds…", choices: ["Only websites", "Native mobile apps using React", "SQL databases", "CSS-only themes"], correctIndex: 1 },
    { id: "rn-q2", prompt: "Core components include…", choices: ["div and span only", "View, Text, Image", "SELECT and JOIN", "iframe only"], correctIndex: 1 },
    { id: "rn-q3", prompt: "StyleSheet.create is used to…", choices: ["Query Postgres", "Define reusable styles", "Commit Git", "Run Paystack"], correctIndex: 1 },
    { id: "rn-q4", prompt: "Flexbox in RN defaults to…", choices: ["row", "column", "grid", "absolute only"], correctIndex: 1 },
    { id: "rn-q5", prompt: "Navigation libraries help you…", choices: ["Style CSS only", "Move between screens", "Encrypt disks", "Write SQL"], correctIndex: 1 },
    { id: "rn-q6", prompt: "Platform-specific code can use…", choices: ["Only HTML comments", "Platform.OS or .ios.js / .android.js files", "Git ignore only", "DNS"], correctIndex: 1 },
    { id: "rn-q7", prompt: "AsyncStorage is for…", choices: ["Server SQL", "Simple local key-value persistence", "CDN caching only", "Certificates"], correctIndex: 1 },
    { id: "rn-q8", prompt: "Testing on real devices matters because…", choices: ["Emulators are always identical", "Performance and sensors differ from desktop", "RN only runs on servers", "Git requires it"], correctIndex: 1 },
  ],
  "devops-docker": [
    { id: "dk-q1", prompt: "A container packages…", choices: ["Only CSS", "App code with its runtime dependencies", "A physical server", "Git history only"], correctIndex: 1 },
    { id: "dk-q2", prompt: "A Dockerfile defines…", choices: ["SQL schema only", "How to build an image", "Paystack keys", "React props"], correctIndex: 1 },
    { id: "dk-q3", prompt: "docker compose is useful for…", choices: ["Single file CSS", "Multi-service local stacks", "Replacing Git", "Only mobile apps"], correctIndex: 1 },
    { id: "dk-q4", prompt: "An image is…", choices: ["A running process", "An immutable template for containers", "A database row", "A certificate"], correctIndex: 1 },
    { id: "dk-q5", prompt: "Volumes help with…", choices: ["Deleting code", "Persisting data outside the container filesystem", "Styling UI", "DNS"], correctIndex: 1 },
    { id: "dk-q6", prompt: "CI typically means…", choices: ["Creative Illustrator", "Continuous Integration of changes with automated checks", "Certificate Issue only", "CSS Inline"], correctIndex: 1 },
    { id: "dk-q7", prompt: "Pinning base image versions helps…", choices: ["Random builds", "Reproducible builds", "Faster CSS", "Skip tests always"], correctIndex: 1 },
    { id: "dk-q8", prompt: "Healthchecks tell orchestrators…", choices: ["Font size", "Whether a container is ready/alive", "Git branch name", "Quiz scores"], correctIndex: 1 },
  ],
  "ai-prompt-engineering": [
    { id: "ai-q1", prompt: "A good prompt is usually…", choices: ["Vague one word", "Specific about goal, format, and constraints", "Only emojis", "SQL only"], correctIndex: 1 },
    { id: "ai-q2", prompt: "Few-shot prompting means…", choices: ["No examples", "Providing a few input/output examples", "Training a new model from scratch always", "Deleting context"], correctIndex: 1 },
    { id: "ai-q3", prompt: "System / role instructions help…", choices: ["Style CSS", "Set behavior and boundaries for the model", "Compile TypeScript", "Host Docker"], correctIndex: 1 },
    { id: "ai-q4", prompt: "Hallucinations are…", choices: ["Perfect facts always", "Plausible but incorrect model outputs", "Git merge conflicts", "CSS bugs only"], correctIndex: 1 },
    { id: "ai-q5", prompt: "You should verify AI code by…", choices: ["Shipping blindly", "Running tests and reading critical paths", "Deleting reviews", "Only checking fonts"], correctIndex: 1 },
    { id: "ai-q6", prompt: "Context windows limit…", choices: ["Disk size only", "How much text the model can consider at once", "Number of CSS files", "Paystack amount"], correctIndex: 1 },
    { id: "ai-q7", prompt: "Chain-of-thought style prompts ask the model to…", choices: ["Skip reasoning", "Show intermediate reasoning steps when helpful", "Only output binary", "Ignore format"], correctIndex: 1 },
    { id: "ai-q8", prompt: "Sensitive data in prompts should be…", choices: ["Pasted freely always", "Avoided or redacted", "Committed to Git", "Emailed publicly"], correctIndex: 1 },
  ],
};

export function getQuizForCourse(courseSlug: string): QuizQuestion[] | null {
  return COURSE_QUIZ_BANKS[courseSlug] ?? null;
}
